# Generated by Django 5.2.1 on 2025-05-22 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cashflowrecord',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='transaction_type',
        ),
        migrations.RenameField(
            model_name='cashflowrecord',
            old_name='custom_date',
            new_name='manual_date',
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow_app.category'),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow_app.status'),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow_app.subcategory'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow_app.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='cashflowrecord',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow_app.type'),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashflow_app.type'),
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
