# Generated by Django 5.2.1 on 2025-05-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow_app', '0002_type_remove_cashflowrecord_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflowrecord',
            options={'verbose_name': 'Запись ДДС', 'verbose_name_plural': 'Записи ДДС'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
    ]
